### ISSUE TITLE
Error with nested block comments

### ISSUE THREAD

**Issue by zommiommy** [mvisani/SQL-minifier#1]
Hi! Currently the crate cannot handle this case:
```sql
SELECT */* SELECT * FROM /*table4*/ table2; */ FROM table1;
```
which should be minified to:
```sql
Select * FROM table1;
```
but instead is minified as:
```sql
SELECT * table2; */ FROM table1;
```

This is because of line 76 of minifier.rs. A regex cannot capture the problem of nested blocks (excluding abusing the regex extensions). You probably want to write a recursive parser for this.

**Comment by zommiommy** [comment]
This is a classical computer science problem, it's basically this: https://en.wikipedia.org/wiki/Dyck_language .

So you want to implement something like:
```rust
let mut depth = 0;
loop {
    if query.startswith("/*") {
        depth += 1;
        query = &query[2..];
        continue;
    } else if query.startswith("*/") {
        depth -= 1;
        query = &query[2..];
        continue;
    }
    if depth == 0 {
       // we are not in a comment
    } else {
       // we are in a comment
    }
    query = &query[1..];
} 
```

**Comment by LucaCappelletti94** [comment]
Handled
